In [1]:
import tensorflow as tf
%load_ext tensorboard
import logging
logging.getLogger('tensorflow').setLevel(logging.ERROR)

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd 
import seaborn as sns
from scipy import stats 
from scipy import linalg

In [2]:
print(tf.__version__)

1.15.0


-----

**In-class Exercise**

1. Create a graph that produces a 3x4 matrix, where an op is added to the default graph and you:

    - add a node A as a matrix of shape [3,2] with some constants 
    - add a node B as a matrix opened to take variables of type float32 (use placeholder)
    - add an operation of their product to the graph producing an output matrix of shape [3,4]
    - print the resulting matrix on the screen

In [3]:
#node A
a = tf.constant(np.array([[1,2.],[3,4],[5,6.]], 
                         dtype=np.float32),
               name = "node_A")

#node B
b = tf.placeholder(dtype = tf.float32, name = "node_B")
product = tf.matmul(a,b)

with tf.Session() as sess:
    input_dict = {b: [[2.,6,9,2.],[8,2,2,4]]}
    result = sess.run(product, feed_dict = input_dict)
    print(result)

[[18. 10. 13. 10.]
 [38. 26. 35. 22.]
 [58. 42. 57. 34.]]


In [4]:
sess = tf.Session()
result = tf.math.pow(2,2)
print(sess.run(result))
print(result.dtype)

4
<dtype: 'int32'>


In [ ]:
t