In [54]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
%load_ext tensorboard


import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd 
import seaborn as sns
from scipy import stats 
from scipy import linalg

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [55]:
print(tf.__version__)

2.1.0


**Linear Algebra**

- Vector
    - is a mathematical object that has a direction and a magnitude, used to find the position of one point in space relative to another point
    - is a computer object, an array of data with individual items located with a single index
- Matrix 
    - is a 2-dimensional (rectangular) **array** of elements represented by symbols, numbers, or expressions, all arranged in rows and columns. 
    - Matrix consist of vectors
- Array
    - is arrangement or series of elements such as symbols, numbers, or expressions. 
    - Arrays can be n-dimensional, so matrix is an array with 2 dimensions
- Tensor
    - is an object describing the **linear relationship** among scalars, vectors, and other tensors
 - Rank
     - of a matrix is the maximum number of linearly independent column (or row) vectors in the matrix

----

**An example of a matrix**

In [3]:
a = np.mat([[2, -4,6], [-12,5,1], [-3,8,4]]) #numpy package to create a matrix
a

matrix([[  2,  -4,   6],
        [-12,   5,   1],
        [ -3,   8,   4]])

In [4]:
b = np.mat([[2],[8], [-4]])
b

matrix([[ 2],
        [ 8],
        [-4]])

In [5]:
a * b

matrix([[-52],
        [ 12],
        [ 42]])

-----

**An example of arrays** 

In [6]:
c = np.zeros(shape=(4,5))
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
d = np.empty(shape=(2,2))
d

array([[1., 1.],
       [1., 0.]])

In [8]:
# a matrix with random complex floats
random_mat = np.ndarray(shape=(2,3), dtype=complex, offset=np.float_().itemsize, order='C')
print(random_mat)



[[-1.49166815e-154-2.00389908e+000j  2.96439388e-323+6.94059315e-310j
   2.45217466e-314+6.94059518e-310j]
 [ 2.45217466e-314+2.45217466e-314j  0.00000000e+000+4.94065646e-323j
   2.33419537e-313+8.97666689e-309j]]


In [9]:
a

matrix([[  2,  -4,   6],
        [-12,   5,   1],
        [ -3,   8,   4]])

In [10]:
a.size 

9

In [11]:
a.shape

(3, 3)

In [12]:
type(a)

numpy.matrix

In [13]:
a.dtype

dtype('int64')

In [14]:
a[2,2]

4

In [15]:
a #original

matrix([[  2,  -4,   6],
        [-12,   5,   1],
        [ -3,   8,   4]])

In [16]:
type(a)

numpy.matrix

In [17]:
a.I #inverse

matrix([[-0.01869159, -0.09968847,  0.0529595 ],
        [-0.07009346, -0.04049844,  0.1152648 ],
        [ 0.12616822,  0.00623053,  0.05919003]])

In [18]:
a.T #transpose

matrix([[  2, -12,  -3],
        [ -4,   5,   8],
        [  6,   1,   4]])

In [19]:
a.H #conjugate transpose

matrix([[  2, -12,  -3],
        [ -4,   5,   8],
        [  6,   1,   4]])

In [20]:
d = np.array([[2,3],[4,5]])
d #original array

array([[2, 3],
       [4, 5]])

In [21]:
type(d)

numpy.ndarray

In [22]:
linalg.inv(d) #calculate the inverse of a matrix

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [23]:
d2 = np.array([[5,6],[7,8]])
d2

array([[5, 6],
       [7, 8]])

In [24]:
d.dot(d2.T) # this is matrix multiplication using dot product function 

array([[28, 38],
       [50, 68]])

In [25]:
d2

array([[5, 6],
       [7, 8]])

In [26]:
linalg.inv(d2)

array([[-4. ,  3. ],
       [ 3.5, -2.5]])

In [27]:
d2 * linalg.inv(d2)

array([[-20. ,  18. ],
       [ 24.5, -20. ]])

----

**Creating a one dimensional array**

In [28]:
tensor_1D = np.array([2,4,5,6,7], dtype = 'int32')
print(tensor_1D)

[2 4 5 6 7]


----

**Creating a two dimensional array**

In [29]:
tensor_2D = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype ='int32')
print(tensor_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


----

**Creating a multi-dimensional array**

In [30]:
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype ='int32')
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [31]:
np.linalg.matrix_rank(m1)

2

In [32]:
m2 = 2 * np.array([[1,2,3],[4,5,6],[7,8,9]], dtype ='int32')
m2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]], dtype=int32)

----

**Converting numpy arrays to tensorflow**


In [33]:
m1 = tf.constant(m1)
m1

<tf.Tensor 'Const:0' shape=(3, 3) dtype=int32>

In [34]:
m2 = tf.constant(m2)
m2

<tf.Tensor 'Const_1:0' shape=(3, 3) dtype=int32>

In [35]:
with tf.Session() as sess:
    print(sess.run(m1))
    print(sess.run(m2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


---

**Matrix Multiplication**

In [36]:
m_product = tf.matmul(m1, m2)
sess = tf.Session()
print(sess.run(m_product))



[[ 60  72  84]
 [132 162 192]
 [204 252 300]]


---

**Matrix Sum**

In [37]:
m_sum = tf.add(m1,m2 )
sess = tf.Session()
print(sess.run(m_sum))

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


----
**Matrix Determinant**


In [38]:
m3 = np.array([[4,5,6],[3,4,1],[2,0,1]], dtype ='float32')
m_det = tf.matrix_determinant(m3)
sess = tf.Session()
print(sess.run(m_det))

-37.000004


---

**TensorFlow Strings**


In [39]:
#TensorFlow Strings
x = tf.constant("This is a String")
print(x)
x = tf.decode_raw(x, tf.uint8)
y = x[:4]

sess = tf.Session()
print(sess.run(y))#this is the same as .eval for 1.x
print("T    H    I    S ")

Tensor("Const_2:0", shape=(), dtype=string)
[ 84 104 105 115]
T    H    I    S 


----
**Converting Numpy Types to TensorFlow Objects**


In [40]:
# converting a scalar to a tensorflow object of float16
D = 92
print(type(D))
D = tf.convert_to_tensor(D, dtype=tf.float16)
sess = tf.Session()
D
#print(sess.run(D))
#D.dtype

<class 'int'>


<tf.Tensor 'Const_3:0' shape=() dtype=float16>

----
**Interactive Session**

- The only difference with a regular 'Session' is that an Interactive Session installs itself as the default session on construction



In [41]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
print(c.eval())
sess.close()



30.0


----

**Using TensorBoard and building our first graph**

In [42]:
# To clear the defined variables and operations of the previous cell
tf.reset_default_graph()


# Let's define our input nodes:
a = tf.constant(5, name="input_a")
b = tf.constant(3, name ="input_b")

#Defining the next two nodes in our graph:
c = tf.multiply(a,b, name="mul_c")
d = tf.add(a,b, name = "add_d")

# this last line defines the final node in our graph
e = tf.add(c,d, name = 'add_e')

In [43]:
# creating the writer out of the session
# writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())

# launch the graph in a session
with tf.Session() as sess:
    # or creating the writer inside the session
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(c))

15


In [45]:
tensorboard --logdir="./graphs" 

Reusing TensorBoard on port 6007 (pid 1160), started 0:07:02 ago. (Use '!kill 1160' to kill it.)

**Placeholders and Feed_dict**

In [47]:
#Basic constant operations
# The value returned by the constructor represents the output of the constant op

a = tf.constant(2)
b = tf.constant(3)

#Launch the default graph
with tf.Session() as sess:
    print("a=2, b=3")
    print("Addition with constants: %i" % sess.run(a+b))
    print("Multiplication with constants: %i" %sess.run(a*b))



a=2, b=3
Addition with constants: 5
Multiplication with constants: 6


In [50]:
# Basic Operations with variable as graph input
# The value returned by the constructor represents the output of the Variable op 
#(define as input when running session)
# tf Graph input

a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)


#Define some operations 
add = tf.add(a,b)
mul = tf.multiply(a,b)

#Launch the default graph
with tf.Session() as sess:
    print("a=2, b=3")
    print("Addition with constants: %i" % sess.run(add, feed_dict={a: 2, b: 3}))
    print("Multiplication with constants: %i" %sess.run(mul, feed_dict={a: 2, b: 3}))




a=2, b=3
Addition with constants: 5
Multiplication with constants: 6


----

**Class Exercise**

1. Create a graph that produces a 3x4 matrix, where you:
    - add nodes A and B as matrices with some floating-point constants
    - add an operation of their product to the graph producing an output matrix of shape [3,4]
    - print the resulting matrix on the screen


In [53]:
sess = tf.InteractiveSession()
matrix1 = tf.constant([[3., 4],[4,5],[6,8]]) #3x2
matrix2 = tf.constant([[2.,6,9,2.],[8,2,2,4]]) #2x4

product = tf.matmul(matrix1, matrix2)
print(product.eval())
sess.close()


[[38. 26. 35. 22.]
 [48. 34. 46. 28.]
 [76. 52. 70. 44.]]
